### ISSUE TITLE
SHOVEl?

### ISSUE THREAD

**Issue by dsabecky** [EmosewaPixel/ExpertModeCore#17]
https://github.com/EmosewaPixel/ExpertModeCore/blob/61a98c4bd82ee3a55b4dfcbf77c8c38d58529a63/src/main/java/com/EmosewaPixel/expertmodecore/items/ItemRegistry.java#L214

I noticed all the SHOVEL variables end in lower case L, not sure if that was intended and/or would cause any issues.

**Comment by TheLimePixel** [comment]
That was fixed in refactoring.
