### ISSUE TITLE
Stone Dust texture very hard to see

### ISSUE THREAD

**Issue by dsabecky** [EmosewaPixel/ExpertModeCore#4]
Using default resource pack, Stone dust is very hard to see as it's almost the same color as inventory backgrounds.

**Comment by dsabecky** [comment]
Possibly adding a border to the texture as a minimal "fix" ?

**Comment by 5ully** [comment]
Tried making a bit of a darker version:
![stone_dust_new](https://user-images.githubusercontent.com/9050688/55820592-bd41ad80-5afb-11e9-9900-7122e2899038.png)
