### ISSUE TITLE
Tool durability checked before block action

### ISSUE THREAD

**Issue by dsabecky** [EmosewaPixel/ExpertModeCore#5]
When using an axe on wood, if the durability changes to 0, the block isn't updated.

Example: Breaking stone with a pickaxe. Pickaxe has durability of 1. Use pickaxe on Stone. Pickaxe breaks at the end of the animation. Stone breaks.

Breaking wood with an axe (hatchet). Hatchet has durability of 1. Use axe on wood. Axe breaks at the end of the animation. Wood doesn't break.

**Comment by TheLimePixel** [comment]
Yeah, how it works is what drops depends on what the player is holding. I can't really do anything about it.
