### ISSUE TITLE
Wood Logs and Wood Planks have same burn rate.

### ISSUE THREAD

**Issue by dsabecky** [EmosewaPixel/ExpertModeCore#6]
Wood Logs and Wood Planks have the same burn rate of 1.5 items.

**Comment by TheLimePixel** [comment]
Well, that's a vanilla thing, you know. Though, changing it since it's an expert pack wouldn't be a bad idea.

**Comment by TheLimePixel** [comment]
Apparently you can't really do that in 1.13.
