### ISSUE TITLE
Steel plate texture

### ISSUE THREAD

**Issue by 5ully** [EmosewaPixel/ExpertModeCore#7]
Would it be possible to get make the steel plate texture a bit darker, or a border? Its a bit hard to see in JEI recipe for crusher.

**Comment by TheLimePixel** [comment]
Well, I need someone to make a better base texture.

**Comment by 5ully** [comment]
Ill try making a updated texture, based on the old texture but with the ingots color:

![steel_plate_new](https://user-images.githubusercontent.com/9050688/55686538-df53f800-5962-11e9-8e21-6a6bbad48436.png)

**Comment by pxoxd** [comment]
actually the edge is way to dark here

**Comment by TheLimePixel** [comment]
Yeah, that looks a bit better
